# Generated by Django 5.0.2 on 2024-02-12 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("item_group", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("cost", models.FloatField()),
                ("linked_sales_order_group", models.CharField(max_length=255)),
                ("creation_date_group", models.DateField()),
                ("completion_date_group", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "build",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("tags", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=255)),
                ("in_stock", models.IntegerField()),
                ("available_stock", models.IntegerField()),
            ],
            options={
                "db_table": "item",
            },
        ),
        migrations.CreateModel(
            name="ItemInDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_allocated", models.CharField(max_length=255)),
                ("allocated_to_builds", models.CharField(max_length=255)),
                ("allocated_to_sales", models.CharField(max_length=255)),
                ("incoming_stock", models.CharField(max_length=255)),
                ("on_build_order", models.CharField(max_length=255)),
                ("net_stock", models.CharField(max_length=255)),
                ("can_build", models.CharField(max_length=255)),
                ("cost", models.FloatField()),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="djangoApp.item"
                    ),
                ),
            ],
            options={
                "db_table": "item_details",
            },
        ),
    ]
